# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test 🧪🔬👩‍🔬

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Restore dependencies
      run: dotnet restore source/C3C.Updater.sln

    - name: Build Solution
      run: dotnet build source/C3C.Updater.sln --no-restore

    - name: Run SharePoint Tests 
      run: dotnet test tests/C3C.Updater.SharePoint_UnitTests/C3C.Updater.SharePoint_UnitTests.csproj --no-build --verbosity normal

    - name: Run SDK Tests 
      run: dotnet test tests/C3C.Updater.SDK_IntegrationTests/C3C.Updater.SDK_IntegrationTests.csproj --no-build --verbosity normal

    - name: Run WebAPI Integration Tests
      run: dotnet test tests/C3C.Updater.Tests/C3C.Updater_Integration_Tests.csproj --verbosity normal